---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  /todos:
    get:
      summary: Retrieve all todos
      responses:
        '200':
          description: List of todos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
components:
  schemas:
    Todo:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
servers:
  - url: https://{defaultHost}
    variables:
      defaultHost:
        default: todo-api.fly.dev
